name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou" #替换成你自己的数据库名字
database_id = "69302f03-acb4-441f-a56c-07207f93f474" #替换成你自己的数据库id

[version_metadata]
binding = "CF_VERSION_METADATA"
